sudo: required
services:
    - docker

before_install:
    - docker build -t zagorh/udemy-react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true zagorh/udemy-react-test npm test

after_success:
    - docker build -t zagorh/udemy-multi-client ./client
    - docker build -t zagorh/udemy-multi-nginx ./nginx
    - docker build -t zagorh/udemy-multi-server ./server
    - docker build -t zagorh/udemy-multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push zagorh/udemy-multi-client
    - docker push zagorh/udemy-multi-nginx
    - docker push zagorh/udemy-multi-server
    - docker push zagorh/udemy-multi-worker